[package]
name = "com-port-plotter"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27.2"
egui = "0.27.2"
egui_plot = "0.27.2"
egui_extras = "0.27.2"
serialport = "4.8.1"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
csv = "1.4.0"
serde = {version = "1.0.228", features = ["derive"]}
